listen=NO
listen_ipv6=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
chroot_local_user=YES
allow_writeable_chroot=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
user_config_dir=/etc/vsftpd.d/bytebay-users
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
utf8_filesystem=YES
